name: Build, Test, and Release

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  release:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: true

      - name: Build Release Binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o easy-tunnel-lb-agent-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o easy-tunnel-lb-agent-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o easy-tunnel-lb-agent-darwin-arm64

      - name: Generate Release Tag
        id: tag
        run: |
          echo "tag_name=v$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          name: Release ${{ steps.tag.outputs.tag_name }}
          files: |
            easy-tunnel-lb-agent-linux-amd64
            easy-tunnel-lb-agent-darwin-amd64
            easy-tunnel-lb-agent-darwin-arm64
          draft: false
          prerelease: false
          generate_release_notes: true
